{% set version = "0.2.1" %}

package:
  name: percol
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/percol/percol-{{ version }}.tar.gz
  sha256: 7a649c6fae61635519d12a6bcacc742241aad1bff3230baef2cedd693ed9cfe8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - cmigemo
    - python >={{ python_min }}
    - six >=1.7.3
    - __unix

test:
  commands:
    - pip check
  imports:
    - percol
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/mooz/percol
  license: MIT
  license_file: LICENSE
  summary: Adds flavor of interactive filtering to the traditional pipe concept of shell

extra:
  recipe-maintainers:
    - danielnachun
